/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class MatchResult : TBase
{
  private long _winnerId;
  private double _elapsedTimeSec;

  public long WinnerId
  {
    get
    {
      return _winnerId;
    }
    set
    {
      __isset.winnerId = true;
      this._winnerId = value;
    }
  }

  public double ElapsedTimeSec
  {
    get
    {
      return _elapsedTimeSec;
    }
    set
    {
      __isset.elapsedTimeSec = true;
      this._elapsedTimeSec = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool winnerId;
    public bool elapsedTimeSec;
  }

  public MatchResult() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I64) {
            WinnerId = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.Double) {
            ElapsedTimeSec = iprot.ReadDouble();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("MatchResult");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.winnerId) {
      field.Name = "winnerId";
      field.Type = TType.I64;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(WinnerId);
      oprot.WriteFieldEnd();
    }
    if (__isset.elapsedTimeSec) {
      field.Name = "elapsedTimeSec";
      field.Type = TType.Double;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteDouble(ElapsedTimeSec);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("MatchResult(");
    bool __first = true;
    if (__isset.winnerId) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("WinnerId: ");
      __sb.Append(WinnerId);
    }
    if (__isset.elapsedTimeSec) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ElapsedTimeSec: ");
      __sb.Append(ElapsedTimeSec);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

