/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class StateChange : TBase
{
  private State _targetState;
  private int _duration;

  /// <summary>
  /// 
  /// <seealso cref="State"/>
  /// </summary>
  public State TargetState
  {
    get
    {
      return _targetState;
    }
    set
    {
      __isset.targetState = true;
      this._targetState = value;
    }
  }

  public int Duration
  {
    get
    {
      return _duration;
    }
    set
    {
      __isset.duration = true;
      this._duration = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool targetState;
    public bool duration;
  }

  public StateChange() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.I32) {
            TargetState = (State)iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.I32) {
            Duration = iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("StateChange");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (__isset.targetState) {
      field.Name = "targetState";
      field.Type = TType.I32;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)TargetState);
      oprot.WriteFieldEnd();
    }
    if (__isset.duration) {
      field.Name = "duration";
      field.Type = TType.I32;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32(Duration);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("StateChange(");
    bool __first = true;
    if (__isset.targetState) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("TargetState: ");
      __sb.Append(TargetState);
    }
    if (__isset.duration) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Duration: ");
      __sb.Append(Duration);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

