/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum State
{
  IDLE = 1,
  MOVING = 2,
  CASTING = 3,
  TACKLING = 4,
  DEAD = 5,
}
