// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actor_list.proto

package com.madratz.serialization;

public final class ActorList {
  private ActorList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional float x = 1;</code>
     */
    float getX();

    /**
     * <code>optional float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional float y = 2;</code>
     */
    float getY();

    /**
     * <code>optional float angle = 3;</code>
     */
    boolean hasAngle();
    /**
     * <code>optional float angle = 3;</code>
     */
    float getAngle();
  }
  /**
   * Protobuf type {@code serialization.Position}
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.Position)
      PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Position(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }

    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              angle_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.madratz.serialization.ActorList.internal_static_serialization_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.madratz.serialization.ActorList.internal_static_serialization_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.madratz.serialization.ActorList.Position.class, com.madratz.serialization.ActorList.Position.Builder.class);
    }

    public static com.google.protobuf.Parser<Position> PARSER =
        new com.google.protobuf.AbstractParser<Position>() {
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>optional float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>optional float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int ANGLE_FIELD_NUMBER = 3;
    private float angle_;
    /**
     * <code>optional float angle = 3;</code>
     */
    public boolean hasAngle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float angle = 3;</code>
     */
    public float getAngle() {
      return angle_;
    }

    private void initFields() {
      x_ = 0F;
      y_ = 0F;
      angle_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, angle_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, angle_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.madratz.serialization.ActorList.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.madratz.serialization.ActorList.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.ActorList.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.madratz.serialization.ActorList.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.Position)
        com.madratz.serialization.ActorList.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.madratz.serialization.ActorList.Position.class, com.madratz.serialization.ActorList.Position.Builder.class);
      }

      // Construct using com.madratz.serialization.ActorList.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        angle_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Position_descriptor;
      }

      public com.madratz.serialization.ActorList.Position getDefaultInstanceForType() {
        return com.madratz.serialization.ActorList.Position.getDefaultInstance();
      }

      public com.madratz.serialization.ActorList.Position build() {
        com.madratz.serialization.ActorList.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.madratz.serialization.ActorList.Position buildPartial() {
        com.madratz.serialization.ActorList.Position result = new com.madratz.serialization.ActorList.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.angle_ = angle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.madratz.serialization.ActorList.Position) {
          return mergeFrom((com.madratz.serialization.ActorList.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.madratz.serialization.ActorList.Position other) {
        if (other == com.madratz.serialization.ActorList.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasAngle()) {
          setAngle(other.getAngle());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.madratz.serialization.ActorList.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.madratz.serialization.ActorList.Position) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>optional float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>optional float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>optional float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>optional float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float angle_ ;
      /**
       * <code>optional float angle = 3;</code>
       */
      public boolean hasAngle() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float angle = 3;</code>
       */
      public float getAngle() {
        return angle_;
      }
      /**
       * <code>optional float angle = 3;</code>
       */
      public Builder setAngle(float value) {
        bitField0_ |= 0x00000004;
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float angle = 3;</code>
       */
      public Builder clearAngle() {
        bitField0_ = (bitField0_ & ~0x00000004);
        angle_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serialization.Position)
    }

    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.Position)
  }

  public interface ActorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.Actor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional .serialization.Position position = 2;</code>
     *
     * <pre>
     *position of center of mass.
     * </pre>
     */
    boolean hasPosition();
    /**
     * <code>optional .serialization.Position position = 2;</code>
     *
     * <pre>
     *position of center of mass.
     * </pre>
     */
    com.madratz.serialization.ActorList.Position getPosition();
    /**
     * <code>optional .serialization.Position position = 2;</code>
     *
     * <pre>
     *position of center of mass.
     * </pre>
     */
    com.madratz.serialization.ActorList.PositionOrBuilder getPositionOrBuilder();

    /**
     * <code>optional float hp = 3;</code>
     */
    boolean hasHp();
    /**
     * <code>optional float hp = 3;</code>
     */
    float getHp();

    /**
     * <code>optional float width = 4;</code>
     */
    boolean hasWidth();
    /**
     * <code>optional float width = 4;</code>
     */
    float getWidth();
  }
  /**
   * Protobuf type {@code serialization.Actor}
   */
  public static final class Actor extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.Actor)
      ActorOrBuilder {
    // Use Actor.newBuilder() to construct.
    private Actor(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Actor(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Actor defaultInstance;
    public static Actor getDefaultInstance() {
      return defaultInstance;
    }

    public Actor getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Actor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.madratz.serialization.ActorList.Position.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = position_.toBuilder();
              }
              position_ = input.readMessage(com.madratz.serialization.ActorList.Position.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(position_);
                position_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              hp_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              width_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.madratz.serialization.ActorList.internal_static_serialization_Actor_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.madratz.serialization.ActorList.internal_static_serialization_Actor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.madratz.serialization.ActorList.Actor.class, com.madratz.serialization.ActorList.Actor.Builder.class);
    }

    public static com.google.protobuf.Parser<Actor> PARSER =
        new com.google.protobuf.AbstractParser<Actor>() {
      public Actor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Actor(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Actor> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private com.madratz.serialization.ActorList.Position position_;
    /**
     * <code>optional .serialization.Position position = 2;</code>
     *
     * <pre>
     *position of center of mass.
     * </pre>
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .serialization.Position position = 2;</code>
     *
     * <pre>
     *position of center of mass.
     * </pre>
     */
    public com.madratz.serialization.ActorList.Position getPosition() {
      return position_;
    }
    /**
     * <code>optional .serialization.Position position = 2;</code>
     *
     * <pre>
     *position of center of mass.
     * </pre>
     */
    public com.madratz.serialization.ActorList.PositionOrBuilder getPositionOrBuilder() {
      return position_;
    }

    public static final int HP_FIELD_NUMBER = 3;
    private float hp_;
    /**
     * <code>optional float hp = 3;</code>
     */
    public boolean hasHp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float hp = 3;</code>
     */
    public float getHp() {
      return hp_;
    }

    public static final int WIDTH_FIELD_NUMBER = 4;
    private float width_;
    /**
     * <code>optional float width = 4;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float width = 4;</code>
     */
    public float getWidth() {
      return width_;
    }

    private void initFields() {
      id_ = 0;
      position_ = com.madratz.serialization.ActorList.Position.getDefaultInstance();
      hp_ = 0F;
      width_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, position_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, hp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, width_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, position_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, hp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, width_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.madratz.serialization.ActorList.Actor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.madratz.serialization.ActorList.Actor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.ActorList.Actor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.madratz.serialization.ActorList.Actor prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.Actor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.Actor)
        com.madratz.serialization.ActorList.ActorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Actor_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Actor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.madratz.serialization.ActorList.Actor.class, com.madratz.serialization.ActorList.Actor.Builder.class);
      }

      // Construct using com.madratz.serialization.ActorList.Actor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (positionBuilder_ == null) {
          position_ = com.madratz.serialization.ActorList.Position.getDefaultInstance();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        hp_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Actor_descriptor;
      }

      public com.madratz.serialization.ActorList.Actor getDefaultInstanceForType() {
        return com.madratz.serialization.ActorList.Actor.getDefaultInstance();
      }

      public com.madratz.serialization.ActorList.Actor build() {
        com.madratz.serialization.ActorList.Actor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.madratz.serialization.ActorList.Actor buildPartial() {
        com.madratz.serialization.ActorList.Actor result = new com.madratz.serialization.ActorList.Actor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hp_ = hp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.width_ = width_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.madratz.serialization.ActorList.Actor) {
          return mergeFrom((com.madratz.serialization.ActorList.Actor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.madratz.serialization.ActorList.Actor other) {
        if (other == com.madratz.serialization.ActorList.Actor.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        if (other.hasHp()) {
          setHp(other.getHp());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.madratz.serialization.ActorList.Actor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.madratz.serialization.ActorList.Actor) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.madratz.serialization.ActorList.Position position_ = com.madratz.serialization.ActorList.Position.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.madratz.serialization.ActorList.Position, com.madratz.serialization.ActorList.Position.Builder, com.madratz.serialization.ActorList.PositionOrBuilder> positionBuilder_;
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public com.madratz.serialization.ActorList.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public Builder setPosition(com.madratz.serialization.ActorList.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public Builder setPosition(
          com.madratz.serialization.ActorList.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public Builder mergePosition(com.madratz.serialization.ActorList.Position value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              position_ != com.madratz.serialization.ActorList.Position.getDefaultInstance()) {
            position_ =
              com.madratz.serialization.ActorList.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = com.madratz.serialization.ActorList.Position.getDefaultInstance();
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public com.madratz.serialization.ActorList.Position.Builder getPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      public com.madratz.serialization.ActorList.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_;
        }
      }
      /**
       * <code>optional .serialization.Position position = 2;</code>
       *
       * <pre>
       *position of center of mass.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.madratz.serialization.ActorList.Position, com.madratz.serialization.ActorList.Position.Builder, com.madratz.serialization.ActorList.PositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.madratz.serialization.ActorList.Position, com.madratz.serialization.ActorList.Position.Builder, com.madratz.serialization.ActorList.PositionOrBuilder>(
                  getPosition(),
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }

      private float hp_ ;
      /**
       * <code>optional float hp = 3;</code>
       */
      public boolean hasHp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float hp = 3;</code>
       */
      public float getHp() {
        return hp_;
      }
      /**
       * <code>optional float hp = 3;</code>
       */
      public Builder setHp(float value) {
        bitField0_ |= 0x00000004;
        hp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float hp = 3;</code>
       */
      public Builder clearHp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hp_ = 0F;
        onChanged();
        return this;
      }

      private float width_ ;
      /**
       * <code>optional float width = 4;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float width = 4;</code>
       */
      public float getWidth() {
        return width_;
      }
      /**
       * <code>optional float width = 4;</code>
       */
      public Builder setWidth(float value) {
        bitField0_ |= 0x00000008;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float width = 4;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        width_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:serialization.Actor)
    }

    static {
      defaultInstance = new Actor(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.Actor)
  }

  public interface ActorsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.Actors)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    java.util.List<com.madratz.serialization.ActorList.Actor> 
        getActorList();
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    com.madratz.serialization.ActorList.Actor getActor(int index);
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    int getActorCount();
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    java.util.List<? extends com.madratz.serialization.ActorList.ActorOrBuilder> 
        getActorOrBuilderList();
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    com.madratz.serialization.ActorList.ActorOrBuilder getActorOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code serialization.Actors}
   */
  public static final class Actors extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.Actors)
      ActorsOrBuilder {
    // Use Actors.newBuilder() to construct.
    private Actors(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Actors(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Actors defaultInstance;
    public static Actors getDefaultInstance() {
      return defaultInstance;
    }

    public Actors getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Actors(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                actor_ = new java.util.ArrayList<com.madratz.serialization.ActorList.Actor>();
                mutable_bitField0_ |= 0x00000001;
              }
              actor_.add(input.readMessage(com.madratz.serialization.ActorList.Actor.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          actor_ = java.util.Collections.unmodifiableList(actor_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.madratz.serialization.ActorList.internal_static_serialization_Actors_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.madratz.serialization.ActorList.internal_static_serialization_Actors_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.madratz.serialization.ActorList.Actors.class, com.madratz.serialization.ActorList.Actors.Builder.class);
    }

    public static com.google.protobuf.Parser<Actors> PARSER =
        new com.google.protobuf.AbstractParser<Actors>() {
      public Actors parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Actors(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Actors> getParserForType() {
      return PARSER;
    }

    public static final int ACTOR_FIELD_NUMBER = 1;
    private java.util.List<com.madratz.serialization.ActorList.Actor> actor_;
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    public java.util.List<com.madratz.serialization.ActorList.Actor> getActorList() {
      return actor_;
    }
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    public java.util.List<? extends com.madratz.serialization.ActorList.ActorOrBuilder> 
        getActorOrBuilderList() {
      return actor_;
    }
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    public int getActorCount() {
      return actor_.size();
    }
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    public com.madratz.serialization.ActorList.Actor getActor(int index) {
      return actor_.get(index);
    }
    /**
     * <code>repeated .serialization.Actor actor = 1;</code>
     */
    public com.madratz.serialization.ActorList.ActorOrBuilder getActorOrBuilder(
        int index) {
      return actor_.get(index);
    }

    private void initFields() {
      actor_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < actor_.size(); i++) {
        output.writeMessage(1, actor_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < actor_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, actor_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.madratz.serialization.ActorList.Actors parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actors parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.madratz.serialization.ActorList.Actors parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.ActorList.Actors parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.madratz.serialization.ActorList.Actors prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.Actors}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.Actors)
        com.madratz.serialization.ActorList.ActorsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Actors_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Actors_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.madratz.serialization.ActorList.Actors.class, com.madratz.serialization.ActorList.Actors.Builder.class);
      }

      // Construct using com.madratz.serialization.ActorList.Actors.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (actorBuilder_ == null) {
          actor_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          actorBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.madratz.serialization.ActorList.internal_static_serialization_Actors_descriptor;
      }

      public com.madratz.serialization.ActorList.Actors getDefaultInstanceForType() {
        return com.madratz.serialization.ActorList.Actors.getDefaultInstance();
      }

      public com.madratz.serialization.ActorList.Actors build() {
        com.madratz.serialization.ActorList.Actors result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.madratz.serialization.ActorList.Actors buildPartial() {
        com.madratz.serialization.ActorList.Actors result = new com.madratz.serialization.ActorList.Actors(this);
        int from_bitField0_ = bitField0_;
        if (actorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            actor_ = java.util.Collections.unmodifiableList(actor_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.actor_ = actor_;
        } else {
          result.actor_ = actorBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.madratz.serialization.ActorList.Actors) {
          return mergeFrom((com.madratz.serialization.ActorList.Actors)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.madratz.serialization.ActorList.Actors other) {
        if (other == com.madratz.serialization.ActorList.Actors.getDefaultInstance()) return this;
        if (actorBuilder_ == null) {
          if (!other.actor_.isEmpty()) {
            if (actor_.isEmpty()) {
              actor_ = other.actor_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureActorIsMutable();
              actor_.addAll(other.actor_);
            }
            onChanged();
          }
        } else {
          if (!other.actor_.isEmpty()) {
            if (actorBuilder_.isEmpty()) {
              actorBuilder_.dispose();
              actorBuilder_ = null;
              actor_ = other.actor_;
              bitField0_ = (bitField0_ & ~0x00000001);
              actorBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getActorFieldBuilder() : null;
            } else {
              actorBuilder_.addAllMessages(other.actor_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.madratz.serialization.ActorList.Actors parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.madratz.serialization.ActorList.Actors) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.madratz.serialization.ActorList.Actor> actor_ =
        java.util.Collections.emptyList();
      private void ensureActorIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          actor_ = new java.util.ArrayList<com.madratz.serialization.ActorList.Actor>(actor_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.madratz.serialization.ActorList.Actor, com.madratz.serialization.ActorList.Actor.Builder, com.madratz.serialization.ActorList.ActorOrBuilder> actorBuilder_;

      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public java.util.List<com.madratz.serialization.ActorList.Actor> getActorList() {
        if (actorBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actor_);
        } else {
          return actorBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public int getActorCount() {
        if (actorBuilder_ == null) {
          return actor_.size();
        } else {
          return actorBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.Actor getActor(int index) {
        if (actorBuilder_ == null) {
          return actor_.get(index);
        } else {
          return actorBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder setActor(
          int index, com.madratz.serialization.ActorList.Actor value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorIsMutable();
          actor_.set(index, value);
          onChanged();
        } else {
          actorBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder setActor(
          int index, com.madratz.serialization.ActorList.Actor.Builder builderForValue) {
        if (actorBuilder_ == null) {
          ensureActorIsMutable();
          actor_.set(index, builderForValue.build());
          onChanged();
        } else {
          actorBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder addActor(com.madratz.serialization.ActorList.Actor value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorIsMutable();
          actor_.add(value);
          onChanged();
        } else {
          actorBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder addActor(
          int index, com.madratz.serialization.ActorList.Actor value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorIsMutable();
          actor_.add(index, value);
          onChanged();
        } else {
          actorBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder addActor(
          com.madratz.serialization.ActorList.Actor.Builder builderForValue) {
        if (actorBuilder_ == null) {
          ensureActorIsMutable();
          actor_.add(builderForValue.build());
          onChanged();
        } else {
          actorBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder addActor(
          int index, com.madratz.serialization.ActorList.Actor.Builder builderForValue) {
        if (actorBuilder_ == null) {
          ensureActorIsMutable();
          actor_.add(index, builderForValue.build());
          onChanged();
        } else {
          actorBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder addAllActor(
          java.lang.Iterable<? extends com.madratz.serialization.ActorList.Actor> values) {
        if (actorBuilder_ == null) {
          ensureActorIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actor_);
          onChanged();
        } else {
          actorBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder clearActor() {
        if (actorBuilder_ == null) {
          actor_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          actorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public Builder removeActor(int index) {
        if (actorBuilder_ == null) {
          ensureActorIsMutable();
          actor_.remove(index);
          onChanged();
        } else {
          actorBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.Actor.Builder getActorBuilder(
          int index) {
        return getActorFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.ActorOrBuilder getActorOrBuilder(
          int index) {
        if (actorBuilder_ == null) {
          return actor_.get(index);  } else {
          return actorBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public java.util.List<? extends com.madratz.serialization.ActorList.ActorOrBuilder> 
           getActorOrBuilderList() {
        if (actorBuilder_ != null) {
          return actorBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actor_);
        }
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.Actor.Builder addActorBuilder() {
        return getActorFieldBuilder().addBuilder(
            com.madratz.serialization.ActorList.Actor.getDefaultInstance());
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.Actor.Builder addActorBuilder(
          int index) {
        return getActorFieldBuilder().addBuilder(
            index, com.madratz.serialization.ActorList.Actor.getDefaultInstance());
      }
      /**
       * <code>repeated .serialization.Actor actor = 1;</code>
       */
      public java.util.List<com.madratz.serialization.ActorList.Actor.Builder> 
           getActorBuilderList() {
        return getActorFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.madratz.serialization.ActorList.Actor, com.madratz.serialization.ActorList.Actor.Builder, com.madratz.serialization.ActorList.ActorOrBuilder> 
          getActorFieldBuilder() {
        if (actorBuilder_ == null) {
          actorBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.madratz.serialization.ActorList.Actor, com.madratz.serialization.ActorList.Actor.Builder, com.madratz.serialization.ActorList.ActorOrBuilder>(
                  actor_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          actor_ = null;
        }
        return actorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:serialization.Actors)
    }

    static {
      defaultInstance = new Actors(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.Actors)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_Actor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_Actor_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_Actors_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_Actors_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020actor_list.proto\022\rserialization\"/\n\010Pos" +
      "ition\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\r\n\005angle\030\003 \001" +
      "(\002\"Y\n\005Actor\022\n\n\002id\030\001 \001(\005\022)\n\010position\030\002 \001(" +
      "\0132\027.serialization.Position\022\n\n\002hp\030\003 \001(\002\022\r" +
      "\n\005width\030\004 \001(\002\"-\n\006Actors\022#\n\005actor\030\001 \003(\0132\024" +
      ".serialization.ActorB\033\n\031com.madratz.seri" +
      "alization"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serialization_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serialization_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_Position_descriptor,
        new java.lang.String[] { "X", "Y", "Angle", });
    internal_static_serialization_Actor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serialization_Actor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_Actor_descriptor,
        new java.lang.String[] { "Id", "Position", "Hp", "Width", });
    internal_static_serialization_Actors_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_serialization_Actors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_Actors_descriptor,
        new java.lang.String[] { "Actor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
