// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: madratz_world.proto

package com.madratz.serialization;

public final class MadratzWorld {
  private MadratzWorld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WorldOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.World)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .serialization.Actors actor = 1;</code>
     */
    boolean hasActor();
    /**
     * <code>optional .serialization.Actors actor = 1;</code>
     */
    com.madratz.serialization.ActorList.Actors getActor();
    /**
     * <code>optional .serialization.Actors actor = 1;</code>
     */
    com.madratz.serialization.ActorList.ActorsOrBuilder getActorOrBuilder();
  }
  /**
   * Protobuf type {@code serialization.World}
   */
  public static final class World extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:serialization.World)
      WorldOrBuilder {
    // Use World.newBuilder() to construct.
    private World(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private World(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final World defaultInstance;
    public static World getDefaultInstance() {
      return defaultInstance;
    }

    public World getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private World(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.madratz.serialization.ActorList.Actors.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = actor_.toBuilder();
              }
              actor_ = input.readMessage(com.madratz.serialization.ActorList.Actors.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(actor_);
                actor_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.madratz.serialization.MadratzWorld.internal_static_serialization_World_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.madratz.serialization.MadratzWorld.internal_static_serialization_World_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.madratz.serialization.MadratzWorld.World.class, com.madratz.serialization.MadratzWorld.World.Builder.class);
    }

    public static com.google.protobuf.Parser<World> PARSER =
        new com.google.protobuf.AbstractParser<World>() {
      public World parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new World(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<World> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ACTOR_FIELD_NUMBER = 1;
    private com.madratz.serialization.ActorList.Actors actor_;
    /**
     * <code>optional .serialization.Actors actor = 1;</code>
     */
    public boolean hasActor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .serialization.Actors actor = 1;</code>
     */
    public com.madratz.serialization.ActorList.Actors getActor() {
      return actor_;
    }
    /**
     * <code>optional .serialization.Actors actor = 1;</code>
     */
    public com.madratz.serialization.ActorList.ActorsOrBuilder getActorOrBuilder() {
      return actor_;
    }

    private void initFields() {
      actor_ = com.madratz.serialization.ActorList.Actors.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, actor_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, actor_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.madratz.serialization.MadratzWorld.World parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.MadratzWorld.World parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.madratz.serialization.MadratzWorld.World parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.madratz.serialization.MadratzWorld.World parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.madratz.serialization.MadratzWorld.World prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.World}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.World)
        com.madratz.serialization.MadratzWorld.WorldOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.madratz.serialization.MadratzWorld.internal_static_serialization_World_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.madratz.serialization.MadratzWorld.internal_static_serialization_World_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.madratz.serialization.MadratzWorld.World.class, com.madratz.serialization.MadratzWorld.World.Builder.class);
      }

      // Construct using com.madratz.serialization.MadratzWorld.World.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (actorBuilder_ == null) {
          actor_ = com.madratz.serialization.ActorList.Actors.getDefaultInstance();
        } else {
          actorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.madratz.serialization.MadratzWorld.internal_static_serialization_World_descriptor;
      }

      public com.madratz.serialization.MadratzWorld.World getDefaultInstanceForType() {
        return com.madratz.serialization.MadratzWorld.World.getDefaultInstance();
      }

      public com.madratz.serialization.MadratzWorld.World build() {
        com.madratz.serialization.MadratzWorld.World result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.madratz.serialization.MadratzWorld.World buildPartial() {
        com.madratz.serialization.MadratzWorld.World result = new com.madratz.serialization.MadratzWorld.World(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (actorBuilder_ == null) {
          result.actor_ = actor_;
        } else {
          result.actor_ = actorBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.madratz.serialization.MadratzWorld.World) {
          return mergeFrom((com.madratz.serialization.MadratzWorld.World)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.madratz.serialization.MadratzWorld.World other) {
        if (other == com.madratz.serialization.MadratzWorld.World.getDefaultInstance()) return this;
        if (other.hasActor()) {
          mergeActor(other.getActor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.madratz.serialization.MadratzWorld.World parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.madratz.serialization.MadratzWorld.World) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.madratz.serialization.ActorList.Actors actor_ = com.madratz.serialization.ActorList.Actors.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.madratz.serialization.ActorList.Actors, com.madratz.serialization.ActorList.Actors.Builder, com.madratz.serialization.ActorList.ActorsOrBuilder> actorBuilder_;
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public boolean hasActor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.Actors getActor() {
        if (actorBuilder_ == null) {
          return actor_;
        } else {
          return actorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public Builder setActor(com.madratz.serialization.ActorList.Actors value) {
        if (actorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          actor_ = value;
          onChanged();
        } else {
          actorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public Builder setActor(
          com.madratz.serialization.ActorList.Actors.Builder builderForValue) {
        if (actorBuilder_ == null) {
          actor_ = builderForValue.build();
          onChanged();
        } else {
          actorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public Builder mergeActor(com.madratz.serialization.ActorList.Actors value) {
        if (actorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              actor_ != com.madratz.serialization.ActorList.Actors.getDefaultInstance()) {
            actor_ =
              com.madratz.serialization.ActorList.Actors.newBuilder(actor_).mergeFrom(value).buildPartial();
          } else {
            actor_ = value;
          }
          onChanged();
        } else {
          actorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public Builder clearActor() {
        if (actorBuilder_ == null) {
          actor_ = com.madratz.serialization.ActorList.Actors.getDefaultInstance();
          onChanged();
        } else {
          actorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.Actors.Builder getActorBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getActorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      public com.madratz.serialization.ActorList.ActorsOrBuilder getActorOrBuilder() {
        if (actorBuilder_ != null) {
          return actorBuilder_.getMessageOrBuilder();
        } else {
          return actor_;
        }
      }
      /**
       * <code>optional .serialization.Actors actor = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.madratz.serialization.ActorList.Actors, com.madratz.serialization.ActorList.Actors.Builder, com.madratz.serialization.ActorList.ActorsOrBuilder> 
          getActorFieldBuilder() {
        if (actorBuilder_ == null) {
          actorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.madratz.serialization.ActorList.Actors, com.madratz.serialization.ActorList.Actors.Builder, com.madratz.serialization.ActorList.ActorsOrBuilder>(
                  getActor(),
                  getParentForChildren(),
                  isClean());
          actor_ = null;
        }
        return actorBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:serialization.World)
    }

    static {
      defaultInstance = new World(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:serialization.World)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_World_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialization_World_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023madratz_world.proto\022\rserialization\032\020ac" +
      "tor_list.proto\"-\n\005World\022$\n\005actor\030\001 \001(\0132\025" +
      ".serialization.ActorsB\033\n\031com.madratz.ser" +
      "ialization"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.madratz.serialization.ActorList.getDescriptor(),
        }, assigner);
    internal_static_serialization_World_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serialization_World_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_serialization_World_descriptor,
        new java.lang.String[] { "Actor", });
    com.madratz.serialization.ActorList.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
